### ISSUE TITLE
With no green letters and one or more yellow letters, "no go" letters have no effect

### ISSUE THREAD

**Issue by havremunken** [trabus/wordle-finder#7]
Hi there,

Looked at this with interest as an Ember dev myself, and noticed one thing. Clicking the letters of the keyboard to say "this letter is not part of the solution" eliminates words containing them from the candidate list, as long as there are no green letters, and there is at least one yellow letter.

I have not yet been able to narrow it down any further than that.

So if you add a yellow letter, you will see that a certain number of words match yours. Simple reproduction example:

- Add a "G" as a yellow (found) character. 571 word candidates are found.
- Click "A", "B", and "E" on the keyboard. This should eliminate plenty of candidates, right? Still 571, many of them containing "A", "B" and/or "E".
- Drag "U" to green slot #2. We're down to 22 possible words, none of them containing "A", "B" or "E". 

So my conclusion so far is that one or more yellow characters with no green characters causes the "character elimination" not to work.

**Comment by trabus** [comment]
Thanks for filing this! I am aware of the bug and have it fixed in a refactor I'm working on. I have just been using this as a creative coding project to have some fun with Ember again. The ultimate problem was that the way I am checking for words is by combining all the letters into one string, then sorting it and using that as a key. When you add more than 5 letters, it can't find a key and just uses the excluded letters to derive which ones to display.

**Comment by havremunken** [comment]
I see I had a typo in my initial report, but you got the issue anyway. Great job fixing this, even if I am looking at the project more to see how people are really using Ember than solving Wordle riddles. :D

**Comment by trabus** [comment]
Pretty sure I fixed this, please reopen if not! Thanks for reporting!
